// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhigaegceftzmyxivfph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoaWdhZWdjZWZ0em15eGl2ZnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTQ3MDUsImV4cCI6MjA3NDM3MDcwNX0.fNvkuyd3kcVqHnSmTrzBP-KJ-j63sLtGmfk15kBzdAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});